baseURL = 'https://article-band.uk'
languageCode = 'en-gb'
title = 'Article - Band'
theme = 'ananke'
publishDir = "public"
buildFuture = true
[params]
  cover_dimming_class = "bg-transparent"
  custom_css = ["css/custom.css"]
  [params.ananke]
    show_recent_posts = false
  [params.ananke.home]
    content_alignment = "left"

[caches]
    [caches.images]
        dir = ':cacheDir/images'
[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "gigs"
        name = "Gigs"
        url = "/gigs/"
        weight = 2
    [[menu.main]]
        identifier = "releases"
        name = "Releases"
        url = "/releases/"
        weight = 3
